name: core
description: Core module dùng chung cho các app Flutter của bạn
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.1
  connectivity_plus: ^6.0.2
  intl: ^0.19.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_lints: ^5.0.0
